worker_processes auto;
error_log /dev/stderr warn;

events {
    worker_connections 4096;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    
    access_log /dev/stdout combined;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;

    # resolver for dynamic proxy_pass
    resolver 8.8.8.8 114.114.114.114 ipv6=off;

    server {
        listen 8095;
        server_name localhost;

        # 默认路由转发给 FastAPI (uvicorn)
        location / {
            proxy_pass http://127.0.0.1:8096;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 内部路由：拦截 FastAPI 返回的 X-Accel-Redirect，接管真实代理下载任务
        location /internal_115_proxy/ {
            internal; # 只能通过内部跳转访问

            # 获取来自 FastAPI 的变量（HTTP头自动转为小写并带上 http_ 前缀）
            set $target_url $upstream_http_x_target_url;
            set $target_ua $upstream_http_x_target_ua;

            # 隐藏一些没用的后端响应头
            proxy_hide_header Content-Disposition;
            
            # 使用 HTTP/1.1 并清空 Connection 头以支持长连接，这对于视频流复用连接极其重要
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            
            # 伪装 UA 和强制关闭压缩，彻底断绝因 gzip 引起的分块错位
            proxy_set_header User-Agent $target_ua;
            proxy_set_header Accept-Encoding identity;
            
            # 允许 Nginx 为 HTTPS 的上游服务器验证 SNI（Server Name Indication）
            proxy_ssl_server_name on;
            
            # 进行动态 URL 代理
            proxy_pass $target_url;
        }
    }
}
