[project]
name = "python-strm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=23.0.0",
    "aiosqlite>=0.20.0",
    "apscheduler>=3.10.0",
    "cryptography>=41.0.0",
    "fastapi>=0.115.0",
    "guessit>=3.8.0",
    "httpx[socks]>=0.27.0",
    "jinja2>=3.1.0",
    "loguru>=0.7.0",
    "p115client>=0.0.8",
    "paramiko>=3.4.0",
    "parsett>=1.8.5",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "pytest>=9.0.3",
    "pytest-asyncio>=1.4.0",
    "python-multipart>=0.0.9",
    "python-socks[asyncio]>=2.4.4",
    "pyyaml>=6.0.0",
    "telethon>=1.33.1",
    "tmdbv3api>=1.9.0",
    "uvicorn[standard]>=0.30.0",
    "websockets>=12.0",
    "x123pan>=0.0.1",
]
